[project]
name = "pelican-htpy"
version = "2026.0"
description = "A Pelican plugin that adds support for htpy templates"
readme = "README.md"
authors = [
    { name = "William Jackson", email = "william@subtlecoolness.com" }
]
requires-python = ">=3.14"
dependencies = [
    "htpy>=26.5.1",
    "markupsafe>=3.0.3",
    "pelican>=4.12.0",
]

[project.scripts]
pelican-htpy = "pelican.plugins.htpy:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "ty>=0.0.80",
]

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pelican.plugins.htpy"

[tool.ruff.lint]
extend-select = ["ANN", "E", "F", "FURB", "I", "PERF", "Q", "RSE", "RUF", "S", "UP"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]  # Pytest uses assertions to verify behavior.
